Update index.ts
fix emrorr tsc :v

src/Socket/index.ts:45:7 - error TS2345: Argument of type '{ version: WAVersion; printQRInTerminal: boolean; auth: AuthenticationState; logger: Logger<{ level: string; }>; msgRetryCounterMap: {}; markOnlineOnConnect: false; browser: [...]; }' is not assignable to parameter of type 'UserFacingSocketConfig'.
  Object literal may only specify known properties, but 'msgRetryCounterMap' does not exist in type 'UserFacingSocketConfig'. Did you mean to write 'msgRetryCounterCache'?

45       msgRetryCounterMap,
         ~~~~~~~~~~~~~~~~~~


Found 1 error in src/Socket/index.ts:45